// Code generated by "xcweaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package xcweaver

import (
	"context"
	"errors"
	"github.com/XCWeaver/xcweaver/runtime/codegen"
	"github.com/XCWeaver/xcweaver/runtime/protos"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/XCWeaver/xcweaver/deployerControl",
		Iface: reflect.TypeOf((*deployerControl)(nil)).Elem(),
		Impl:  reflect.TypeOf(localDeployerControl{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return deployerControl_local_stub{impl: impl.(deployerControl), tracer: tracer, activateComponentMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "ActivateComponent", Remote: false, Generated: true}), exportListenerMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "ExportListener", Remote: false, Generated: true}), getAntipodeAgentInfoMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "GetAntipodeAgentInfo", Remote: false, Generated: true}), getListenerAddressMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "GetListenerAddress", Remote: false, Generated: true}), getSelfCertificateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "GetSelfCertificate", Remote: false, Generated: true}), handleTraceSpansMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "HandleTraceSpans", Remote: false, Generated: true}), logBatchMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "LogBatch", Remote: false, Generated: true}), verifyClientCertificateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "VerifyClientCertificate", Remote: false, Generated: true}), verifyServerCertificateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "VerifyServerCertificate", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return deployerControl_client_stub{stub: stub, activateComponentMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "ActivateComponent", Remote: true, Generated: true}), exportListenerMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "ExportListener", Remote: true, Generated: true}), getAntipodeAgentInfoMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "GetAntipodeAgentInfo", Remote: true, Generated: true}), getListenerAddressMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "GetListenerAddress", Remote: true, Generated: true}), getSelfCertificateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "GetSelfCertificate", Remote: true, Generated: true}), handleTraceSpansMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "HandleTraceSpans", Remote: true, Generated: true}), logBatchMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "LogBatch", Remote: true, Generated: true}), verifyClientCertificateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "VerifyClientCertificate", Remote: true, Generated: true}), verifyServerCertificateMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/deployerControl", Method: "VerifyServerCertificate", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return deployerControl_server_stub{impl: impl.(deployerControl), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return deployerControl_reflect_stub{caller: caller}
		},
		RefData: "",
	})
	codegen.Register(codegen.Registration{
		Name:  "github.com/XCWeaver/xcweaver/weaveletControl",
		Iface: reflect.TypeOf((*weaveletControl)(nil)).Elem(),
		Impl:  reflect.TypeOf(noopWeaveletControl{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return weaveletControl_local_stub{impl: impl.(weaveletControl), tracer: tracer, getHealthMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "GetHealth", Remote: false, Generated: true}), getLoadMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "GetLoad", Remote: false, Generated: true}), getMetricsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "GetMetrics", Remote: false, Generated: true}), getProfileMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "GetProfile", Remote: false, Generated: true}), initWeaveletMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "InitWeavelet", Remote: false, Generated: true}), updateComponentsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "UpdateComponents", Remote: false, Generated: true}), updateRoutingInfoMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "UpdateRoutingInfo", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return weaveletControl_client_stub{stub: stub, getHealthMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "GetHealth", Remote: true, Generated: true}), getLoadMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "GetLoad", Remote: true, Generated: true}), getMetricsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "GetMetrics", Remote: true, Generated: true}), getProfileMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "GetProfile", Remote: true, Generated: true}), initWeaveletMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "InitWeavelet", Remote: true, Generated: true}), updateComponentsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "UpdateComponents", Remote: true, Generated: true}), updateRoutingInfoMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/XCWeaver/xcweaver/weaveletControl", Method: "UpdateRoutingInfo", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return weaveletControl_server_stub{impl: impl.(weaveletControl), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return weaveletControl_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// xcweaver.InstanceOf checks.
var _ InstanceOf[deployerControl] = (*localDeployerControl)(nil)
var _ InstanceOf[weaveletControl] = (*noopWeaveletControl)(nil)

// xcweaver.Router checks.
var _ Unrouted = (*localDeployerControl)(nil)
var _ Unrouted = (*noopWeaveletControl)(nil)

// Local stub implementations.

type deployerControl_local_stub struct {
	impl                           deployerControl
	tracer                         trace.Tracer
	activateComponentMetrics       *codegen.MethodMetrics
	exportListenerMetrics          *codegen.MethodMetrics
	getAntipodeAgentInfoMetrics    *codegen.MethodMetrics
	getListenerAddressMetrics      *codegen.MethodMetrics
	getSelfCertificateMetrics      *codegen.MethodMetrics
	handleTraceSpansMetrics        *codegen.MethodMetrics
	logBatchMetrics                *codegen.MethodMetrics
	verifyClientCertificateMetrics *codegen.MethodMetrics
	verifyServerCertificateMetrics *codegen.MethodMetrics
}

// Check that deployerControl_local_stub implements the deployerControl interface.
var _ deployerControl = (*deployerControl_local_stub)(nil)

func (s deployerControl_local_stub) ActivateComponent(ctx context.Context, a0 *protos.ActivateComponentRequest) (r0 *protos.ActivateComponentReply, err error) {
	// Update metrics.
	begin := s.activateComponentMetrics.Begin()
	defer func() { s.activateComponentMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.deployerControl.ActivateComponent", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ActivateComponent(ctx, a0)
}

func (s deployerControl_local_stub) ExportListener(ctx context.Context, a0 *protos.ExportListenerRequest) (r0 *protos.ExportListenerReply, err error) {
	// Update metrics.
	begin := s.exportListenerMetrics.Begin()
	defer func() { s.exportListenerMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.deployerControl.ExportListener", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.ExportListener(ctx, a0)
}

func (s deployerControl_local_stub) GetAntipodeAgentInfo(ctx context.Context, a0 *protos.GetAntipodeAgentInfoRequest) (r0 *protos.GetAntipodeAgentInfoReply, err error) {
	// Update metrics.
	begin := s.getAntipodeAgentInfoMetrics.Begin()
	defer func() { s.getAntipodeAgentInfoMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.deployerControl.GetAntipodeAgentInfo", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetAntipodeAgentInfo(ctx, a0)
}

func (s deployerControl_local_stub) GetListenerAddress(ctx context.Context, a0 *protos.GetListenerAddressRequest) (r0 *protos.GetListenerAddressReply, err error) {
	// Update metrics.
	begin := s.getListenerAddressMetrics.Begin()
	defer func() { s.getListenerAddressMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.deployerControl.GetListenerAddress", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetListenerAddress(ctx, a0)
}

func (s deployerControl_local_stub) GetSelfCertificate(ctx context.Context, a0 *protos.GetSelfCertificateRequest) (r0 *protos.GetSelfCertificateReply, err error) {
	// Update metrics.
	begin := s.getSelfCertificateMetrics.Begin()
	defer func() { s.getSelfCertificateMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.deployerControl.GetSelfCertificate", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetSelfCertificate(ctx, a0)
}

func (s deployerControl_local_stub) HandleTraceSpans(ctx context.Context, a0 *protos.TraceSpans) (err error) {
	// Update metrics.
	begin := s.handleTraceSpansMetrics.Begin()
	defer func() { s.handleTraceSpansMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.deployerControl.HandleTraceSpans", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.HandleTraceSpans(ctx, a0)
}

func (s deployerControl_local_stub) LogBatch(ctx context.Context, a0 *protos.LogEntryBatch) (err error) {
	// Update metrics.
	begin := s.logBatchMetrics.Begin()
	defer func() { s.logBatchMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.deployerControl.LogBatch", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.LogBatch(ctx, a0)
}

func (s deployerControl_local_stub) VerifyClientCertificate(ctx context.Context, a0 *protos.VerifyClientCertificateRequest) (r0 *protos.VerifyClientCertificateReply, err error) {
	// Update metrics.
	begin := s.verifyClientCertificateMetrics.Begin()
	defer func() { s.verifyClientCertificateMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.deployerControl.VerifyClientCertificate", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.VerifyClientCertificate(ctx, a0)
}

func (s deployerControl_local_stub) VerifyServerCertificate(ctx context.Context, a0 *protos.VerifyServerCertificateRequest) (r0 *protos.VerifyServerCertificateReply, err error) {
	// Update metrics.
	begin := s.verifyServerCertificateMetrics.Begin()
	defer func() { s.verifyServerCertificateMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.deployerControl.VerifyServerCertificate", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.VerifyServerCertificate(ctx, a0)
}

type weaveletControl_local_stub struct {
	impl                     weaveletControl
	tracer                   trace.Tracer
	getHealthMetrics         *codegen.MethodMetrics
	getLoadMetrics           *codegen.MethodMetrics
	getMetricsMetrics        *codegen.MethodMetrics
	getProfileMetrics        *codegen.MethodMetrics
	initWeaveletMetrics      *codegen.MethodMetrics
	updateComponentsMetrics  *codegen.MethodMetrics
	updateRoutingInfoMetrics *codegen.MethodMetrics
}

// Check that weaveletControl_local_stub implements the weaveletControl interface.
var _ weaveletControl = (*weaveletControl_local_stub)(nil)

func (s weaveletControl_local_stub) GetHealth(ctx context.Context, a0 *protos.GetHealthRequest) (r0 *protos.GetHealthReply, err error) {
	// Update metrics.
	begin := s.getHealthMetrics.Begin()
	defer func() { s.getHealthMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.weaveletControl.GetHealth", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetHealth(ctx, a0)
}

func (s weaveletControl_local_stub) GetLoad(ctx context.Context, a0 *protos.GetLoadRequest) (r0 *protos.GetLoadReply, err error) {
	// Update metrics.
	begin := s.getLoadMetrics.Begin()
	defer func() { s.getLoadMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.weaveletControl.GetLoad", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetLoad(ctx, a0)
}

func (s weaveletControl_local_stub) GetMetrics(ctx context.Context, a0 *protos.GetMetricsRequest) (r0 *protos.GetMetricsReply, err error) {
	// Update metrics.
	begin := s.getMetricsMetrics.Begin()
	defer func() { s.getMetricsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.weaveletControl.GetMetrics", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetMetrics(ctx, a0)
}

func (s weaveletControl_local_stub) GetProfile(ctx context.Context, a0 *protos.GetProfileRequest) (r0 *protos.GetProfileReply, err error) {
	// Update metrics.
	begin := s.getProfileMetrics.Begin()
	defer func() { s.getProfileMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.weaveletControl.GetProfile", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetProfile(ctx, a0)
}

func (s weaveletControl_local_stub) InitWeavelet(ctx context.Context, a0 *protos.InitWeaveletRequest) (r0 *protos.InitWeaveletReply, err error) {
	// Update metrics.
	begin := s.initWeaveletMetrics.Begin()
	defer func() { s.initWeaveletMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.weaveletControl.InitWeavelet", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.InitWeavelet(ctx, a0)
}

func (s weaveletControl_local_stub) UpdateComponents(ctx context.Context, a0 *protos.UpdateComponentsRequest) (r0 *protos.UpdateComponentsReply, err error) {
	// Update metrics.
	begin := s.updateComponentsMetrics.Begin()
	defer func() { s.updateComponentsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.weaveletControl.UpdateComponents", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.UpdateComponents(ctx, a0)
}

func (s weaveletControl_local_stub) UpdateRoutingInfo(ctx context.Context, a0 *protos.UpdateRoutingInfoRequest) (r0 *protos.UpdateRoutingInfoReply, err error) {
	// Update metrics.
	begin := s.updateRoutingInfoMetrics.Begin()
	defer func() { s.updateRoutingInfoMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "xcweaver.weaveletControl.UpdateRoutingInfo", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.UpdateRoutingInfo(ctx, a0)
}

// Client stub implementations.

type deployerControl_client_stub struct {
	stub                           codegen.Stub
	activateComponentMetrics       *codegen.MethodMetrics
	exportListenerMetrics          *codegen.MethodMetrics
	getAntipodeAgentInfoMetrics    *codegen.MethodMetrics
	getListenerAddressMetrics      *codegen.MethodMetrics
	getSelfCertificateMetrics      *codegen.MethodMetrics
	handleTraceSpansMetrics        *codegen.MethodMetrics
	logBatchMetrics                *codegen.MethodMetrics
	verifyClientCertificateMetrics *codegen.MethodMetrics
	verifyServerCertificateMetrics *codegen.MethodMetrics
}

// Check that deployerControl_client_stub implements the deployerControl interface.
var _ deployerControl = (*deployerControl_client_stub)(nil)

func (s deployerControl_client_stub) ActivateComponent(ctx context.Context, a0 *protos.ActivateComponentRequest) (r0 *protos.ActivateComponentReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.activateComponentMetrics.Begin()
	defer func() { s.activateComponentMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.deployerControl.ActivateComponent", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_ActivateComponentRequest_5a679567(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_ActivateComponentReply_c8006e70(dec)
	err = dec.Error()
	return
}

func (s deployerControl_client_stub) ExportListener(ctx context.Context, a0 *protos.ExportListenerRequest) (r0 *protos.ExportListenerReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.exportListenerMetrics.Begin()
	defer func() { s.exportListenerMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.deployerControl.ExportListener", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_ExportListenerRequest_ebf52349(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_ExportListenerReply_2186e973(dec)
	err = dec.Error()
	return
}

func (s deployerControl_client_stub) GetAntipodeAgentInfo(ctx context.Context, a0 *protos.GetAntipodeAgentInfoRequest) (r0 *protos.GetAntipodeAgentInfoReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getAntipodeAgentInfoMetrics.Begin()
	defer func() { s.getAntipodeAgentInfoMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.deployerControl.GetAntipodeAgentInfo", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetAntipodeAgentInfoRequest_f0e7c1eb(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetAntipodeAgentInfoReply_6b29e231(dec)
	err = dec.Error()
	return
}

func (s deployerControl_client_stub) GetListenerAddress(ctx context.Context, a0 *protos.GetListenerAddressRequest) (r0 *protos.GetListenerAddressReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getListenerAddressMetrics.Begin()
	defer func() { s.getListenerAddressMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.deployerControl.GetListenerAddress", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetListenerAddressRequest_52cc2571(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetListenerAddressReply_132092dd(dec)
	err = dec.Error()
	return
}

func (s deployerControl_client_stub) GetSelfCertificate(ctx context.Context, a0 *protos.GetSelfCertificateRequest) (r0 *protos.GetSelfCertificateReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getSelfCertificateMetrics.Begin()
	defer func() { s.getSelfCertificateMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.deployerControl.GetSelfCertificate", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetSelfCertificateRequest_298c9233(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 4, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetSelfCertificateReply_87752294(dec)
	err = dec.Error()
	return
}

func (s deployerControl_client_stub) HandleTraceSpans(ctx context.Context, a0 *protos.TraceSpans) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.handleTraceSpansMetrics.Begin()
	defer func() { s.handleTraceSpansMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.deployerControl.HandleTraceSpans", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_TraceSpans_86cf317d(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 5, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s deployerControl_client_stub) LogBatch(ctx context.Context, a0 *protos.LogEntryBatch) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.logBatchMetrics.Begin()
	defer func() { s.logBatchMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.deployerControl.LogBatch", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_LogEntryBatch_90b2181c(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 6, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s deployerControl_client_stub) VerifyClientCertificate(ctx context.Context, a0 *protos.VerifyClientCertificateRequest) (r0 *protos.VerifyClientCertificateReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.verifyClientCertificateMetrics.Begin()
	defer func() { s.verifyClientCertificateMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.deployerControl.VerifyClientCertificate", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_VerifyClientCertificateRequest_10a07b68(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 7, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_VerifyClientCertificateReply_38a18f7b(dec)
	err = dec.Error()
	return
}

func (s deployerControl_client_stub) VerifyServerCertificate(ctx context.Context, a0 *protos.VerifyServerCertificateRequest) (r0 *protos.VerifyServerCertificateReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.verifyServerCertificateMetrics.Begin()
	defer func() { s.verifyServerCertificateMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.deployerControl.VerifyServerCertificate", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_VerifyServerCertificateRequest_c9dbdbe8(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 8, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_VerifyServerCertificateReply_975794cc(dec)
	err = dec.Error()
	return
}

type weaveletControl_client_stub struct {
	stub                     codegen.Stub
	getHealthMetrics         *codegen.MethodMetrics
	getLoadMetrics           *codegen.MethodMetrics
	getMetricsMetrics        *codegen.MethodMetrics
	getProfileMetrics        *codegen.MethodMetrics
	initWeaveletMetrics      *codegen.MethodMetrics
	updateComponentsMetrics  *codegen.MethodMetrics
	updateRoutingInfoMetrics *codegen.MethodMetrics
}

// Check that weaveletControl_client_stub implements the weaveletControl interface.
var _ weaveletControl = (*weaveletControl_client_stub)(nil)

func (s weaveletControl_client_stub) GetHealth(ctx context.Context, a0 *protos.GetHealthRequest) (r0 *protos.GetHealthReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getHealthMetrics.Begin()
	defer func() { s.getHealthMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.weaveletControl.GetHealth", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetHealthRequest_675a143c(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetHealthReply_789dfa54(dec)
	err = dec.Error()
	return
}

func (s weaveletControl_client_stub) GetLoad(ctx context.Context, a0 *protos.GetLoadRequest) (r0 *protos.GetLoadReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getLoadMetrics.Begin()
	defer func() { s.getLoadMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.weaveletControl.GetLoad", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetLoadRequest_c33d4a5b(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetLoadReply_d30bf405(dec)
	err = dec.Error()
	return
}

func (s weaveletControl_client_stub) GetMetrics(ctx context.Context, a0 *protos.GetMetricsRequest) (r0 *protos.GetMetricsReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMetricsMetrics.Begin()
	defer func() { s.getMetricsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.weaveletControl.GetMetrics", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetMetricsRequest_ecd4d5f7(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetMetricsReply_340e66b4(dec)
	err = dec.Error()
	return
}

func (s weaveletControl_client_stub) GetProfile(ctx context.Context, a0 *protos.GetProfileRequest) (r0 *protos.GetProfileReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getProfileMetrics.Begin()
	defer func() { s.getProfileMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.weaveletControl.GetProfile", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetProfileRequest_96f3c30d(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetProfileReply_c6dc161a(dec)
	err = dec.Error()
	return
}

func (s weaveletControl_client_stub) InitWeavelet(ctx context.Context, a0 *protos.InitWeaveletRequest) (r0 *protos.InitWeaveletReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.initWeaveletMetrics.Begin()
	defer func() { s.initWeaveletMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.weaveletControl.InitWeavelet", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_InitWeaveletRequest_16114ee6(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 4, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_InitWeaveletReply_ef1e60ed(dec)
	err = dec.Error()
	return
}

func (s weaveletControl_client_stub) UpdateComponents(ctx context.Context, a0 *protos.UpdateComponentsRequest) (r0 *protos.UpdateComponentsReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateComponentsMetrics.Begin()
	defer func() { s.updateComponentsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.weaveletControl.UpdateComponents", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_UpdateComponentsRequest_5e728367(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 5, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_UpdateComponentsReply_07d4e4e3(dec)
	err = dec.Error()
	return
}

func (s weaveletControl_client_stub) UpdateRoutingInfo(ctx context.Context, a0 *protos.UpdateRoutingInfoRequest) (r0 *protos.UpdateRoutingInfoReply, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateRoutingInfoMetrics.Begin()
	defer func() { s.updateRoutingInfoMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "xcweaver.weaveletControl.UpdateRoutingInfo", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_UpdateRoutingInfoRequest_1a1198bc(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 6, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_UpdateRoutingInfoReply_7f3841c5(dec)
	err = dec.Error()
	return
}

// Note that "xcweaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'xcweaver generate' v0.0.2 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/XCWeaver/xcweaver module that you're using. The xcweaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/XCWeaver/xcweaver

We recommend updating the xcweaver module and the 'xcweaver generate' command by
running the following.

    go get github.com/XCWeaver/xcweaver@latest
    go install github.com/XCWeaver/xcweaver/cmd/xcweaver@latest

Then, re-run 'xcweaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/XCWeaver/xcweaver/issues.

`)

// Server stub implementations.

type deployerControl_server_stub struct {
	impl    deployerControl
	addLoad func(key uint64, load float64)
}

// Check that deployerControl_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*deployerControl_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s deployerControl_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "ActivateComponent":
		return s.activateComponent
	case "ExportListener":
		return s.exportListener
	case "GetAntipodeAgentInfo":
		return s.getAntipodeAgentInfo
	case "GetListenerAddress":
		return s.getListenerAddress
	case "GetSelfCertificate":
		return s.getSelfCertificate
	case "HandleTraceSpans":
		return s.handleTraceSpans
	case "LogBatch":
		return s.logBatch
	case "VerifyClientCertificate":
		return s.verifyClientCertificate
	case "VerifyServerCertificate":
		return s.verifyServerCertificate
	default:
		return nil
	}
}

func (s deployerControl_server_stub) activateComponent(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.ActivateComponentRequest
	a0 = serviceweaver_dec_ptr_ActivateComponentRequest_5a679567(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.ActivateComponent(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_ActivateComponentReply_c8006e70(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s deployerControl_server_stub) exportListener(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.ExportListenerRequest
	a0 = serviceweaver_dec_ptr_ExportListenerRequest_ebf52349(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.ExportListener(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_ExportListenerReply_2186e973(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s deployerControl_server_stub) getAntipodeAgentInfo(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.GetAntipodeAgentInfoRequest
	a0 = serviceweaver_dec_ptr_GetAntipodeAgentInfoRequest_f0e7c1eb(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetAntipodeAgentInfo(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetAntipodeAgentInfoReply_6b29e231(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s deployerControl_server_stub) getListenerAddress(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.GetListenerAddressRequest
	a0 = serviceweaver_dec_ptr_GetListenerAddressRequest_52cc2571(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetListenerAddress(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetListenerAddressReply_132092dd(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s deployerControl_server_stub) getSelfCertificate(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.GetSelfCertificateRequest
	a0 = serviceweaver_dec_ptr_GetSelfCertificateRequest_298c9233(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetSelfCertificate(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetSelfCertificateReply_87752294(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s deployerControl_server_stub) handleTraceSpans(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.TraceSpans
	a0 = serviceweaver_dec_ptr_TraceSpans_86cf317d(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.HandleTraceSpans(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s deployerControl_server_stub) logBatch(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.LogEntryBatch
	a0 = serviceweaver_dec_ptr_LogEntryBatch_90b2181c(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.LogBatch(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s deployerControl_server_stub) verifyClientCertificate(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.VerifyClientCertificateRequest
	a0 = serviceweaver_dec_ptr_VerifyClientCertificateRequest_10a07b68(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.VerifyClientCertificate(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_VerifyClientCertificateReply_38a18f7b(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s deployerControl_server_stub) verifyServerCertificate(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.VerifyServerCertificateRequest
	a0 = serviceweaver_dec_ptr_VerifyServerCertificateRequest_c9dbdbe8(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.VerifyServerCertificate(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_VerifyServerCertificateReply_975794cc(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

type weaveletControl_server_stub struct {
	impl    weaveletControl
	addLoad func(key uint64, load float64)
}

// Check that weaveletControl_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*weaveletControl_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s weaveletControl_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "GetHealth":
		return s.getHealth
	case "GetLoad":
		return s.getLoad
	case "GetMetrics":
		return s.getMetrics
	case "GetProfile":
		return s.getProfile
	case "InitWeavelet":
		return s.initWeavelet
	case "UpdateComponents":
		return s.updateComponents
	case "UpdateRoutingInfo":
		return s.updateRoutingInfo
	default:
		return nil
	}
}

func (s weaveletControl_server_stub) getHealth(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.GetHealthRequest
	a0 = serviceweaver_dec_ptr_GetHealthRequest_675a143c(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetHealth(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetHealthReply_789dfa54(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s weaveletControl_server_stub) getLoad(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.GetLoadRequest
	a0 = serviceweaver_dec_ptr_GetLoadRequest_c33d4a5b(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetLoad(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetLoadReply_d30bf405(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s weaveletControl_server_stub) getMetrics(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.GetMetricsRequest
	a0 = serviceweaver_dec_ptr_GetMetricsRequest_ecd4d5f7(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetMetrics(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetMetricsReply_340e66b4(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s weaveletControl_server_stub) getProfile(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.GetProfileRequest
	a0 = serviceweaver_dec_ptr_GetProfileRequest_96f3c30d(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetProfile(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetProfileReply_c6dc161a(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s weaveletControl_server_stub) initWeavelet(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.InitWeaveletRequest
	a0 = serviceweaver_dec_ptr_InitWeaveletRequest_16114ee6(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.InitWeavelet(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_InitWeaveletReply_ef1e60ed(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s weaveletControl_server_stub) updateComponents(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.UpdateComponentsRequest
	a0 = serviceweaver_dec_ptr_UpdateComponentsRequest_5e728367(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.UpdateComponents(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_UpdateComponentsReply_07d4e4e3(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s weaveletControl_server_stub) updateRoutingInfo(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *protos.UpdateRoutingInfoRequest
	a0 = serviceweaver_dec_ptr_UpdateRoutingInfoRequest_1a1198bc(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.UpdateRoutingInfo(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_UpdateRoutingInfoReply_7f3841c5(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type deployerControl_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that deployerControl_reflect_stub implements the deployerControl interface.
var _ deployerControl = (*deployerControl_reflect_stub)(nil)

func (s deployerControl_reflect_stub) ActivateComponent(ctx context.Context, a0 *protos.ActivateComponentRequest) (r0 *protos.ActivateComponentReply, err error) {
	err = s.caller("ActivateComponent", ctx, []any{a0}, []any{&r0})
	return
}

func (s deployerControl_reflect_stub) ExportListener(ctx context.Context, a0 *protos.ExportListenerRequest) (r0 *protos.ExportListenerReply, err error) {
	err = s.caller("ExportListener", ctx, []any{a0}, []any{&r0})
	return
}

func (s deployerControl_reflect_stub) GetAntipodeAgentInfo(ctx context.Context, a0 *protos.GetAntipodeAgentInfoRequest) (r0 *protos.GetAntipodeAgentInfoReply, err error) {
	err = s.caller("GetAntipodeAgentInfo", ctx, []any{a0}, []any{&r0})
	return
}

func (s deployerControl_reflect_stub) GetListenerAddress(ctx context.Context, a0 *protos.GetListenerAddressRequest) (r0 *protos.GetListenerAddressReply, err error) {
	err = s.caller("GetListenerAddress", ctx, []any{a0}, []any{&r0})
	return
}

func (s deployerControl_reflect_stub) GetSelfCertificate(ctx context.Context, a0 *protos.GetSelfCertificateRequest) (r0 *protos.GetSelfCertificateReply, err error) {
	err = s.caller("GetSelfCertificate", ctx, []any{a0}, []any{&r0})
	return
}

func (s deployerControl_reflect_stub) HandleTraceSpans(ctx context.Context, a0 *protos.TraceSpans) (err error) {
	err = s.caller("HandleTraceSpans", ctx, []any{a0}, []any{})
	return
}

func (s deployerControl_reflect_stub) LogBatch(ctx context.Context, a0 *protos.LogEntryBatch) (err error) {
	err = s.caller("LogBatch", ctx, []any{a0}, []any{})
	return
}

func (s deployerControl_reflect_stub) VerifyClientCertificate(ctx context.Context, a0 *protos.VerifyClientCertificateRequest) (r0 *protos.VerifyClientCertificateReply, err error) {
	err = s.caller("VerifyClientCertificate", ctx, []any{a0}, []any{&r0})
	return
}

func (s deployerControl_reflect_stub) VerifyServerCertificate(ctx context.Context, a0 *protos.VerifyServerCertificateRequest) (r0 *protos.VerifyServerCertificateReply, err error) {
	err = s.caller("VerifyServerCertificate", ctx, []any{a0}, []any{&r0})
	return
}

type weaveletControl_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that weaveletControl_reflect_stub implements the weaveletControl interface.
var _ weaveletControl = (*weaveletControl_reflect_stub)(nil)

func (s weaveletControl_reflect_stub) GetHealth(ctx context.Context, a0 *protos.GetHealthRequest) (r0 *protos.GetHealthReply, err error) {
	err = s.caller("GetHealth", ctx, []any{a0}, []any{&r0})
	return
}

func (s weaveletControl_reflect_stub) GetLoad(ctx context.Context, a0 *protos.GetLoadRequest) (r0 *protos.GetLoadReply, err error) {
	err = s.caller("GetLoad", ctx, []any{a0}, []any{&r0})
	return
}

func (s weaveletControl_reflect_stub) GetMetrics(ctx context.Context, a0 *protos.GetMetricsRequest) (r0 *protos.GetMetricsReply, err error) {
	err = s.caller("GetMetrics", ctx, []any{a0}, []any{&r0})
	return
}

func (s weaveletControl_reflect_stub) GetProfile(ctx context.Context, a0 *protos.GetProfileRequest) (r0 *protos.GetProfileReply, err error) {
	err = s.caller("GetProfile", ctx, []any{a0}, []any{&r0})
	return
}

func (s weaveletControl_reflect_stub) InitWeavelet(ctx context.Context, a0 *protos.InitWeaveletRequest) (r0 *protos.InitWeaveletReply, err error) {
	err = s.caller("InitWeavelet", ctx, []any{a0}, []any{&r0})
	return
}

func (s weaveletControl_reflect_stub) UpdateComponents(ctx context.Context, a0 *protos.UpdateComponentsRequest) (r0 *protos.UpdateComponentsReply, err error) {
	err = s.caller("UpdateComponents", ctx, []any{a0}, []any{&r0})
	return
}

func (s weaveletControl_reflect_stub) UpdateRoutingInfo(ctx context.Context, a0 *protos.UpdateRoutingInfoRequest) (r0 *protos.UpdateRoutingInfoReply, err error) {
	err = s.caller("UpdateRoutingInfo", ctx, []any{a0}, []any{&r0})
	return
}

// Encoding/decoding implementations.

func serviceweaver_enc_ptr_ActivateComponentRequest_5a679567(enc *codegen.Encoder, arg *protos.ActivateComponentRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_ActivateComponentRequest_5a679567(dec *codegen.Decoder) *protos.ActivateComponentRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.ActivateComponentRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_ActivateComponentReply_c8006e70(enc *codegen.Encoder, arg *protos.ActivateComponentReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_ActivateComponentReply_c8006e70(dec *codegen.Decoder) *protos.ActivateComponentReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.ActivateComponentReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_ExportListenerRequest_ebf52349(enc *codegen.Encoder, arg *protos.ExportListenerRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_ExportListenerRequest_ebf52349(dec *codegen.Decoder) *protos.ExportListenerRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.ExportListenerRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_ExportListenerReply_2186e973(enc *codegen.Encoder, arg *protos.ExportListenerReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_ExportListenerReply_2186e973(dec *codegen.Decoder) *protos.ExportListenerReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.ExportListenerReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetAntipodeAgentInfoRequest_f0e7c1eb(enc *codegen.Encoder, arg *protos.GetAntipodeAgentInfoRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetAntipodeAgentInfoRequest_f0e7c1eb(dec *codegen.Decoder) *protos.GetAntipodeAgentInfoRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetAntipodeAgentInfoRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetAntipodeAgentInfoReply_6b29e231(enc *codegen.Encoder, arg *protos.GetAntipodeAgentInfoReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetAntipodeAgentInfoReply_6b29e231(dec *codegen.Decoder) *protos.GetAntipodeAgentInfoReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetAntipodeAgentInfoReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetListenerAddressRequest_52cc2571(enc *codegen.Encoder, arg *protos.GetListenerAddressRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetListenerAddressRequest_52cc2571(dec *codegen.Decoder) *protos.GetListenerAddressRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetListenerAddressRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetListenerAddressReply_132092dd(enc *codegen.Encoder, arg *protos.GetListenerAddressReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetListenerAddressReply_132092dd(dec *codegen.Decoder) *protos.GetListenerAddressReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetListenerAddressReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetSelfCertificateRequest_298c9233(enc *codegen.Encoder, arg *protos.GetSelfCertificateRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetSelfCertificateRequest_298c9233(dec *codegen.Decoder) *protos.GetSelfCertificateRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetSelfCertificateRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetSelfCertificateReply_87752294(enc *codegen.Encoder, arg *protos.GetSelfCertificateReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetSelfCertificateReply_87752294(dec *codegen.Decoder) *protos.GetSelfCertificateReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetSelfCertificateReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_TraceSpans_86cf317d(enc *codegen.Encoder, arg *protos.TraceSpans) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_TraceSpans_86cf317d(dec *codegen.Decoder) *protos.TraceSpans {
	if !dec.Bool() {
		return nil
	}
	var res protos.TraceSpans
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_LogEntryBatch_90b2181c(enc *codegen.Encoder, arg *protos.LogEntryBatch) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_LogEntryBatch_90b2181c(dec *codegen.Decoder) *protos.LogEntryBatch {
	if !dec.Bool() {
		return nil
	}
	var res protos.LogEntryBatch
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_VerifyClientCertificateRequest_10a07b68(enc *codegen.Encoder, arg *protos.VerifyClientCertificateRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_VerifyClientCertificateRequest_10a07b68(dec *codegen.Decoder) *protos.VerifyClientCertificateRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.VerifyClientCertificateRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_VerifyClientCertificateReply_38a18f7b(enc *codegen.Encoder, arg *protos.VerifyClientCertificateReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_VerifyClientCertificateReply_38a18f7b(dec *codegen.Decoder) *protos.VerifyClientCertificateReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.VerifyClientCertificateReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_VerifyServerCertificateRequest_c9dbdbe8(enc *codegen.Encoder, arg *protos.VerifyServerCertificateRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_VerifyServerCertificateRequest_c9dbdbe8(dec *codegen.Decoder) *protos.VerifyServerCertificateRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.VerifyServerCertificateRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_VerifyServerCertificateReply_975794cc(enc *codegen.Encoder, arg *protos.VerifyServerCertificateReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_VerifyServerCertificateReply_975794cc(dec *codegen.Decoder) *protos.VerifyServerCertificateReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.VerifyServerCertificateReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetHealthRequest_675a143c(enc *codegen.Encoder, arg *protos.GetHealthRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetHealthRequest_675a143c(dec *codegen.Decoder) *protos.GetHealthRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetHealthRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetHealthReply_789dfa54(enc *codegen.Encoder, arg *protos.GetHealthReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetHealthReply_789dfa54(dec *codegen.Decoder) *protos.GetHealthReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetHealthReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetLoadRequest_c33d4a5b(enc *codegen.Encoder, arg *protos.GetLoadRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetLoadRequest_c33d4a5b(dec *codegen.Decoder) *protos.GetLoadRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetLoadRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetLoadReply_d30bf405(enc *codegen.Encoder, arg *protos.GetLoadReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetLoadReply_d30bf405(dec *codegen.Decoder) *protos.GetLoadReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetLoadReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetMetricsRequest_ecd4d5f7(enc *codegen.Encoder, arg *protos.GetMetricsRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetMetricsRequest_ecd4d5f7(dec *codegen.Decoder) *protos.GetMetricsRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetMetricsRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetMetricsReply_340e66b4(enc *codegen.Encoder, arg *protos.GetMetricsReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetMetricsReply_340e66b4(dec *codegen.Decoder) *protos.GetMetricsReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetMetricsReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetProfileRequest_96f3c30d(enc *codegen.Encoder, arg *protos.GetProfileRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetProfileRequest_96f3c30d(dec *codegen.Decoder) *protos.GetProfileRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetProfileRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetProfileReply_c6dc161a(enc *codegen.Encoder, arg *protos.GetProfileReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetProfileReply_c6dc161a(dec *codegen.Decoder) *protos.GetProfileReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.GetProfileReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_InitWeaveletRequest_16114ee6(enc *codegen.Encoder, arg *protos.InitWeaveletRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_InitWeaveletRequest_16114ee6(dec *codegen.Decoder) *protos.InitWeaveletRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.InitWeaveletRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_InitWeaveletReply_ef1e60ed(enc *codegen.Encoder, arg *protos.InitWeaveletReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_InitWeaveletReply_ef1e60ed(dec *codegen.Decoder) *protos.InitWeaveletReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.InitWeaveletReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_UpdateComponentsRequest_5e728367(enc *codegen.Encoder, arg *protos.UpdateComponentsRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_UpdateComponentsRequest_5e728367(dec *codegen.Decoder) *protos.UpdateComponentsRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.UpdateComponentsRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_UpdateComponentsReply_07d4e4e3(enc *codegen.Encoder, arg *protos.UpdateComponentsReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_UpdateComponentsReply_07d4e4e3(dec *codegen.Decoder) *protos.UpdateComponentsReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.UpdateComponentsReply
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_UpdateRoutingInfoRequest_1a1198bc(enc *codegen.Encoder, arg *protos.UpdateRoutingInfoRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_UpdateRoutingInfoRequest_1a1198bc(dec *codegen.Decoder) *protos.UpdateRoutingInfoRequest {
	if !dec.Bool() {
		return nil
	}
	var res protos.UpdateRoutingInfoRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_UpdateRoutingInfoReply_7f3841c5(enc *codegen.Encoder, arg *protos.UpdateRoutingInfoReply) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_UpdateRoutingInfoReply_7f3841c5(dec *codegen.Decoder) *protos.UpdateRoutingInfoReply {
	if !dec.Bool() {
		return nil
	}
	var res protos.UpdateRoutingInfoReply
	dec.DecodeProto(&res)
	return &res
}
